spring:
  application:
    name=baeshil-baeshil

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      platform: mysql

  jpa:
    properties:
      hibernate:
        ddl-auto: update
    generate-ddl: true
